travis:
  secure:
    BINSTAR_TOKEN: KaTCvOK5XGiRf47mqhdfK4Nsvfw+Tezr5WQYnQFBzHTStppU0+Gpm3SaX54GJYWVgYIdwlaZvB/gu0j2sgYDV0dvzyeqom8WCG8lVsQMYAyHq9gnSNQtM2jujL41f5ngNkHmvwSfyklIfbK03PQd9TzHiRw2p1YG9hU5whvHVcPdkm7+jZ/Tap/3aa2GX03VGXMQm1U3pD/tNtZxCkLeFI6nC9VsqCuodv5rGoCgxWK6o+0/MfxIBsq7wlgUe2oeFbOx2fj8PMavM9dV7A0adIEBizlTePbtT4Td47lLmP5uPciSeHdLvBjC7lxSIS5EmDvzs462KrzTZLGnBQ7ymeWpiswXMsxnJdCelF+vMjGS8t3VFJ3bO6IsMgC4yT14XWnJt4bjouEEffXVQSV//fu51ekWoJFTgPPHbNAFMQlv7lZirJAoeKCp0mcbJ+KiyaQE3EDxysZx4I7yUwh1iA0jckv7s5FG4+E8TD5AQ7xrgGYcVInnbtF6OLbaP2l0NhBLfIwcwHd8isTj6MYmtNVM35ip9SBogL5bmbf5H8Knboof1692CLyq/xwdpjV+Clj29U0LwU7xoR2/wfy/vmW8tX5PaCiN/sligwxX5AV5k/fz0ULkejWCd20VTidSm9hkZZXOYrhcHDrw+FikQR7a/T86Rl9FjhEiyHJwZLM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
